version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: finance_user
      SPRING_DATASOURCE_PASSWORD: finance_password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - postgres
    networks:
      - finance-network
    volumes:
      - .:/app
      - maven-data:/root/.m2

volumes:
  postgres_data:
  maven-data:

networks:
  finance-network:
    driver: bridge