name: Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      finance-test-db:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: finance_test_db
          POSTGRES_USER: finance_test_user
          POSTGRES_PASSWORD: finance_test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn clean package -Dspring.profiles.active=test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/finance_test_db
          SPRING_DATASOURCE_USERNAME: finance_test_user
          SPRING_DATASOURCE_PASSWORD: finance_test_password
          SPRING_JPA_HIBERNATE_DDL-AUTO: create
          SPRING_FLYWAY_ENABLED: true